name: Lighthouse test
on: [push]

jobs:
  lighthouse-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: amondnet/now-deployment@master
        id: now
        with:
          github-comment: false
          zeit-token: ${{ secrets.ZEIT_NOW_TOKEN }}
          now-org-id: ${{ secrets.ZEIT_NOW_ORG_ID }}
          now-project-id: ${{ secrets.ZEIT_NOW_PROJECT_ID }}
      - name: Ping
        run: |
          curl -Is ${{ steps.now.outputs.preview-url }} | head -1
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: ${{ steps.now.outputs.preview-url }}
